# Generated by Django 2.0.7 on 2018-07-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dp',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
